openapi: 3.0.0
info:
  title: user
  version: '1.0'
  contact:
    name: masashi mizuno
  description: |-
    User向けAPI
    認証はCognitoが発行したJWT Tokenを利用する
servers:
  - url: 'https://satellite-office-app.herokuapp.com'
    description: Mock
  - url: 'https://{本番ドメイン}/user/api/v1'
    description: Production
paths:
  /areas:
    get:
      summary: エリア一覧取得
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: エリア一覧
                properties:
                  areas:
                    type: array
                    description: エリアリスト
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: エリアID
                        name:
                          type: string
                          description: エリア名
              examples:
                example:
                  value:
                    areas:
                      - id: 1
                        name: 品川
                      - id: 2
                        name: 渋谷
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: get-areas
      description: エリア一覧を取得する
      tags:
        - ホテル関連
      security:
        - bearerAuth: []

  /users/register:
    post:
      summary: ユーザー登録
      tags:
        - ユーザー認証
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: post-users-register
      description: ユーザー登録API
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                company_id:
                  type: number
                  description: 企業ID
                first_name:
                  type: string
                  description: 名
                last_name:
                  type: string
                  description: 姓
                first_name_kana:
                  type: string
                  description: 名　カナ
                last_name_kana:
                  type: string
                  description: 姓　カナ
                email:
                  type: string
                  description: メールアドレス
                password:
                  type: string
                  description: パスワード
                group_name:
                  type: string
                  description: グループ名
                employee_id:
                  type: string
                  description: 社員ID
              required:
                - company_id
                - first_name
                - last_name
                - first_name_kana
                - last_name_kana
                - email
                - password
  /users/update:
    post:
      summary: ユーザー情報変更
      tags:
        - ユーザー認証
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: post-users-update
      description: ユーザー情報変更API
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: number
                  description: ユーザーID
                first_name:
                  type: string
                  description: 名
                last_name:
                  type: string
                  description: 姓
                first_name_kana:
                  type: string
                  description: 名　カナ
                last_name_kana:
                  type: string
                  description: 姓　カナ
                login_id:
                  type: string
                  description: ログイン用ののメールアドレス（Cognitoのメールアドレス）
                email:
                  type: string
                  description: 連絡用のメールアドレス
                group_name:
                  type: string
                  description: グループ名
                employee_id:
                  type: string
                  description: 社員ID
              required:
                - user_id
                - first_name
                - last_name
                - first_name_kana
                - last_name_kana
                - login_id
                - email
                - group_name
                - employee_id
  /users/confirm:
    post:
      summary: ユーザー認証
      operationId: post-users-confirm
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                properties:
                  success:
                    type: boolean
                  tmp_token:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      description: |-
        ユーザー認証API
        （/users/registerで送信されるメールの記載される認証コードとメールアドレスをPOSTする）
      tags:
        - ユーザー認証
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                verify_code:
                  type: string
              required:
                - email
                - verify_code
        description: ''
  /users/resend_confirm_code:
    post:
      summary: ユーザー認証コードを再発行する
      operationId: post-users-resend-confirm-code
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      description: |-
        ユーザー認証コードを再発行するAPI
        （/users/registerで登録したメールアドレスをPOSTする）
      tags:
        - ユーザー認証
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email
        description: ''
  /users/status:
    get:
      summary: ユーザーステータス取得API
      tags:
        - ユーザー認証
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    description: ユーザーID
                  name:
                    type: string
                    description: ユーザー名
                  company_name:
                    type: string
                    description: 会社名
                  is_check_in:
                    type: boolean
                    description: チェックイン状態
                required:
                  - id
                  - name
                  - company_name
                  - is_check_in
              examples:
                example:
                  value:
                    id: 10
                    name: スズキ太郎
                    company_name: 株式会社テスト
                    is_check_in: true
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: get-users-status
      description: ユーザーステータス取得API
      security:
        - bearerAuth: []

  /login:
    post:
      summary: ログイン
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: number
                    description: ログインしたユーザーのID
                    example: 100
                  user_name:
                    type: string
                    description: ユーザー名
                    example: 鈴木太郎
                  token:
                    type: string
                    description: アクセストークン
                    format: string
                    example: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IuWxseeUsCIsImV4cCI6IjIwMTkvMDQvMDEifQ.u8TT4ySJhBiMod1rNqCxiISXwCXqddVSJE5gncSCGD7RPHigHoZiDnLfwcIIGij-ARBrswe4eluMUgaQwS7FUdN8IVwKkFUY1533TQZZYhTUzobO3q_PnDyPi8cPDmkSTJHzBhT298G7fNZENUUo8fmCjOkYC9FibTMrF6Aij4w
                  is_unauth_user:
                    type: boolean
                    description: |-
                      初回ログインユーザーかどうか
                      初回だった場合はパスワード変更させる
                    example: true
                required:
                  - user_id
                  - user_name
                  - token
                  - is_unauth_user
              examples:
                Example:
                  value:
                    user_id: 1
                    user_name: 太郎
                    token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IuWxseeUsCIsImV4cCI6IjIwMTkvMDQvMDEifQ.u8TT4ySJhBiMod1rNqCxiISXwCXqddVSJE5gncSCGD7RPHigHoZiDnLfwcIIGij-ARBrswe4eluMUgaQwS7FUdN8IVwKkFUY1533TQZZYhTUzobO3q_PnDyPi8cPDmkSTJHzBhT298G7fNZENUUo8fmCjOkYC9FibTMrF6Ai
                    is_unauth_user: true
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: post-login
      description: Cognitoを利用した認証を行う
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 登録メールアドレス
                password:
                  type: string
                  description: ログインパスワード
              required:
                - email
                - password
        description: ''
      tags:
        - ユーザー認証
  /reset_password:
    post:
      summary: パスワードリセット
      tags:
        - ユーザー認証
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: post-reset_password
      description: パスワードリセットを行う
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email
  /change_password:
    post:
      summary: パスワード変更
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: post-change_password
      description: パスワード変更を行う。初回パスワード設定も
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                new_password:
                  type: string
                  description: 新パスワード
              required:
                - new_password
        description: ''
      tags:
        - ユーザー認証

  /hotels:
    get:
      summary: ホテル一覧
      tags:
        - ホテル関連
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result_count:
                    type: number
                    description: 結果件数
                  search_condition:
                    type: string
                    description: 検索条件
                  date:
                    type: string
                    description: 利用日
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: ホテルID
                        name:
                          type: string
                          description: ホテル名
                        address:
                          type: string
                          description: 住所
                        tel:
                          type: string
                          description: 電話番号
                        access:
                          type: string
                          description: 交通アクセス
                        parking:
                          type: string
                          description: 駐車場情報
                        url:
                          type: string
                          description: ホテルURL
                        google_map_url:
                          type: string
                          description: GoogleマップURL
                        facilities:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: number
                                description: 施設ID
                              name:
                                type: string
                                description: 施設名
                              price:
                                type: string
                                description: 利用単価
                              capacity:
                                type: number
                                description: 座席数
                              availability_count:
                                type: number
                                description: 残席数
                              sold_out:
                                type: boolean
                                description: 満席かどうか
                              start_time:
                                type: string
                                description: 予約開始時間
                              end_time:
                                type: string
                                description: 予約終了時間
                              image_url:
                                type: string
                                description: 画像URL
                      required:
                        - id
                        - name
                        - address
                        - tel
                        - access
                        - parking
                        - facilities
                required:
                  - result_count
                  - search_condition
                  - date
              examples:
                example:
                  value:
                    result_count: 3
                    search_condition: 2019/12/31  東京都　品川駅　周辺
                    date: 20191212
                    results:
                      - id: 1
                        name: ホテルA
                        address: 東京都品川区xxxx
                        tel: 03-0000-1111
                        access: ＪＲ線品川駅（高輪口）より徒歩２分
                        parking: '駐車場有り　1,500円（税込み）　先着順'
                        business_hour: '10:00~22:00'
                        url: 'https://sample.com'
                        google_map_url: 'https://www.google.co.jp/maps/'
                        facilities:
                          - id: 1
                            name: 会議室A
                            price: 200
                            capacity: 20
                            availability_count: 10
                            sold_out: false
                            start_time: '1000'
                            end_time: '1300'
                            image_url: 'http://placehold.it/300x300'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: get-hotels
      security:
        - bearerAuth: []
      parameters:
        - schema:
            type: string
          in: query
          name: date
          description: 日付(yyyymmdd)
          required: true
        - schema:
            type: string
          in: query
          name: start_time
          description: 開始時間
        - schema:
            type: string
          in: query
          name: end_time
          description: 終了時間
        - schema:
            type: number
          in: query
          name: area_id
          description: エリアID
        - schema:
            type: string
          in: query
          name: keyword
          description: キーワード
      description: ホテル一覧API
  /hotels/qr:
    get:
      summary: QRコードからホテル情報取得
      tags:
        - ホテル関連
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: ホテルID
                  name:
                    type: string
                    description: ホテル名
                  address:
                    type: string
                    description: 住所
                  tel:
                    type: string
                    description: 電話番号
                  access:
                    type: string
                    description: 交通アクセス
                  parking:
                    type: string
                    description: 駐車場情報
                  url:
                    type: string
                    description: ホテルURL
                  google_map_url:
                    type: string
                    description: GoogleマップURL
              examples:
                example:
                  value:
                    id: 1
                    name: ホテルA
                    address: 東京都品川区xxxx
                    tel: 03-0000-1111
                    access: ＪＲ線品川駅（高輪口）より徒歩２分
                    parking: '駐車場有り　1,500円（税込み）　先着順'
                    url: 'https://sample.com'
                    google_map_url: 'https://www.google.co.jp/maps/'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: get-hotel-qr
      security:
        - bearerAuth: []
      parameters:
        - schema:
            type: string
          in: query
          name: hash
          description: ホテルハッシュ値
          required: true
      description: QRコードからホテル情報取得API
  '/hotels/{id}/facilities':
    get:
      summary: 施設一覧
      tags:
        - ホテル関連
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  facilities:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                          description: 施設ID
                        name:
                          type: string
                          description: 施設名
                        location:
                          type: string
                          description: 館内場所
                      required:
                        - id
                        - name
                        - location
                required:
                  - facilities
              examples:
                example:
                  value:
                    facilities:
                      - id: 1
                        name: 会議室A
                        price: 200
                        capacity: 20
                        availability_count: 10
                        sold_out: false
                        image_url: 'http://placehold.it/300x300'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: get-hotel-facilities
      security:
        - bearerAuth: []
      parameters: []
      description: 施設一覧API
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ホテルID
  '/facility/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: 施設ID
    get:
      summary: 施設利用可能情報API
      tags:
        - ホテル関連
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: 施設名
                  price:
                    type: number
                    description: 単価
                  capacity:
                    type: number
                    description: 座席数
                  equipment:
                    type: string
                    description: 設備
                  image_url:
                    type: string
                    description: 画像URL
                  hotel:
                    $ref: ../models/hotelmodel.v1.yaml
                  time_table:
                    type: array
                    description: 時間ごとの状況
                    items:
                      type: object
                      properties:
                        time:
                          type: string
                          description: 時間
                        availability_count:
                          type: number
                          description: 残席数
                        status:
                          type: number
                          description: |-
                            予約ステータス
                            0: 予約不可
                            1: 予約可
                            2: 空き十分
                      required:
                        - time
                        - availability_count
                        - status
                required:
                  - time_table
                  - name
                  - hotel
              examples:
                example:
                  value:
                    name: 会議室A
                    price: 200
                    capacity: 20
                    equipment: 'インターネット接続無料（有線・無線） / コンセント / プリンター '
                    image_url: 'http://placehold.it/300x300'
                    hotel:
                      id: 100
                      name: ホテルA
                      address: 東京都品川区xxxx
                      tel: 03-0000-1111
                      access: ＪＲ線品川駅（高輪口）より徒歩２分
                      parking: '駐車場有り　1,500円（税込み）　先着順'
                      url: 'https://sample.com'
                      google_map_url: 'https://www.google.co.jp/maps/'
                    time_table:
                      - time: '1030'
                        availability_count: 0
                        status: 0
                      - time: '1045'
                        availability_count: 3
                        status: 1
                      - time: '1100'
                        availability_count: 10
                        status: 2
                      - time: '1115'
                        availability_count: 3
                        status: 1
                      - time: '1130'
                        availability_count: 3
                        status: 1
                      - time: '1145'
                        availability_count: 3
                        status: 1
                      - time: '1200'
                        availability_count: 3
                        status: 1
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: get-facility-availabilities-id
      description: 施設利用可能情報API
      security:
        - bearerAuth: []
      parameters:
        - schema:
            type: string
          in: query
          name: date
          required: true
          description: 日付

  /reservations:
    get:
      summary: 予約一覧_
      tags:
        - 予約
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  reservations:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          description: 予約ID
                          type: number
                        date:
                          type: string
                          description: 利用予定日
                        create_date:
                          type: string
                          description: 予約日
                        hotel:
                          $ref: ../models/hotelmodel.v1.yaml
                        facility:
                          type: object
                          properties:
                            id:
                              type: number
                              description: 施設ID
                            name:
                              type: string
                              description: 施設名
                            price:
                              type: string
                              description: 単価
                        start_time:
                          type: string
                          description: 予約開始時間
                        end_time:
                          type: string
                          description: 予約終了時間
                        is_cancel:
                          type: boolean
                          description: キャンセル可能かどうか
                        check_status:
                          type: number
                          description: |-
                            チェックインアウト状態
                            0: 未チェックイン
                            1: チェックイン済み
                            2: チェックアウト済み
                      required:
                        - id
                        - date
                        - create_date
                        - hotel
                        - start_time
                        - end_time
                        - is_cancel
                        - check_status
                required:
                  - reservations
              examples:
                example:
                  value:
                    reservations:
                      - id: 1
                        date: 20191212
                        hotel:
                          id: 1
                          name: ホテルA
                          address: 東京都品川区xxxx
                          tel: 03-0000-1111
                          access: ＪＲ線品川駅（高輪口）より徒歩２分
                          parking: '駐車場有り　1,500円（税込み）　先着順'
                          url: 'https://sample.com'
                          google_map_url: 'https://www.google.co.jp/maps/'
                        facility:
                          id: 11
                          name: 会議室A
                          price: 300
                        start_time: '1000'
                        end_time: '1300'
                        is_cancel: false
                        is_check_in: true
                        check_status: 1
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: get-reservations
      description: 予約一覧API
      security:
        - bearerAuth: []
      parameters: []
  /reservations/register:
    post:
      summary: 予約登録
      tags:
        - 予約
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  reserve_id:
                    type: number
              examples:
                example:
                  value:
                    reserve_id: 1
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: post-reservations-register
      description: 予約登録API
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                facility_id:
                  type: number
                date:
                  type: string
                start_time:
                  type: string
                end_time:
                  type: string
  /reservations/extend:
    post:
      summary: 延長登録
      tags:
        - 予約
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  reserve_id:
                    type: number
              examples:
                example:
                  value:
                    reserve_id: 1
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: post-reservations-extend
      description: 予約延長API
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reserve_id:
                  type: number
                end_time:
                  type: string
  /reservations/check_in:
    post:
      summary: チェックイン
      tags:
        - 予約
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: post-reservations-check_in
      description: チェックインAPI
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reserve_id:
                  type: string
                  description: 予約ID
                date:
                  type: string
                  description: 'チェックイン日時 YYYYMMDDHHmm'
              required:
                - reserve_id
                - date
    parameters: []
  /reservations/check_out:
    post:
      summary: チェックアウト
      tags:
        - 予約
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: post-reservations-check_out
      description: チェックアウトAPI
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reserve_id:
                  type: string
                  description: 予約ID
                date:
                  type: string
                  description: 'チェックアウト日時 YYYYMMDDHHmm'
              required:
                - reserve_id
                - date
    parameters: []
  '/reservations/cancel/{id}':
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
        description: 予約ID
    delete:
      summary: 予約取り消し
      tags:
        - 予約
      operationId: delete-reservations-cancel-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      description: 予約取り消しAPI
      security:
        - bearerAuth: []
  /reservations/history:
    get:
      summary: 実績一覧
      tags:
        - 予約
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  histories:
                    type: array
                    description: 実績一覧
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                          description: 予約ID
                        date:
                          type: string
                          description: 利用日
                        create_date:
                          type: string
                          description: 予約日
                        hotel:
                          $ref: ../models/hotelmodel.v1.yaml
                        name:
                          type: string
                          description: 施設名
                        price:
                          type: string
                          description: 単価
                        start_time:
                          type: string
                          description: 予約開始時間
                        end_time:
                          type: string
                          description: 予約終了時間
                        check_out_time:
                          type: string
                          description: チェックアウト時間
                        check_in_time:
                          type: string
                          description: チェックイン時間
                      required:
                        - id
                        - date
                        - hotel
                        - name
                        - price
                        - start_time
                        - end_time
                        - is_extend
                        - is_cancel
                        - check_status
                        - create_date
                required:
                  - histories
              examples:
                example:
                  value:
                    histories:
                      - id: 1
                        date: 20191212
                        create_date: 20191210
                        hotel:
                          id: 1
                          name: ホテルA
                          address: 東京都品川区xxxx
                          tel: 03-0000-1111
                          access: ＪＲ線品川駅（高輪口）より徒歩２分
                          parking: '駐車場有り　1,500円（税込み）　先着順'
                          url: 'https://sample.com'
                          google_map_url: 'https://www.google.co.jp/maps/'
                        name: 会議室A
                        price: 200
                        start_time: '1000'
                        end_time: '1300'
                        check_in_time: '1000'
                        check_out_time: '1300'
      operationId: get-histories
      security:
        - bearerAuth: []
      parameters:
        - schema:
            type: number
          in: query
          description: |-
            範囲
            0: 1か月
            1: 3か月
            2: ６か月
            3: １年
          name: range
      description: 実績一覧API
components:
  schemas: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: Bearer
      description: ''
tags:
  - name: ユーザー認証
    description: ユーザーログインに関わるAPI
  - name: ホテル関連
    description: ホテル関連
  - name: 予約
    description: 予約
  - name: 実績
    description: 実績
